lable: config-plus-6
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///micro
    username: root
    password: 1234
  application:
    name: provider
  rabbitmq:
    host: 192.168.3.210
    port: 5672
    username: rabbit
    password: rabbit
