lable: configs
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///5a?useSSL=true&serverTimezone=UTC
    password: 1234
    username: root
  application:
      name: cloud-provider
  
